### ISSUE TITLE
Parsing of Google search results should be asynchronous

### ISSUE THREAD

**Issue by olivierobert** [dvarun/gextract#2]
Upon upload new keyword, an asynchronous job should be created and run later. Rails 4.2 has this [feature built-in](http://weblog.rubyonrails.org/2014/12/19/Rails-4-2-final/) using either Delayed Job (simpler) or Sidekiq.

**Task**
1. Move the logic to parse the search results page from the keywords controller and to a job. 
2. Implement asynchronous processing of the job

**Comment by dvarun** [comment]
Hi Olivier,

I'm working on it, will let you know as soon as I complete it. :)
